name: 'Deps Image'
description: 'Build and publish docker images with deps installed'
author: 'Harvey Rogers'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: node12
  main: dist/index.js
