name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm run build

      - name: Prettier
        uses: harveyr/gh-action-prettier@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      - name: ESLint
        uses: harveyr/gh-action-eslint@releases/v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      # FIXME:
      # - run: npm test

      # - uses: ./

      - run: npm run dist

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist
