name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    if: 'false'
    steps:
    - uses: actions/checkout@v1

    - run: npm ci

    - run: npm run build

    - name: Prettier
      uses: harveyr/gh-action-prettier@releases/v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        patterns: src/**.ts

    - name: ESLint
      uses: harveyr/gh-action-eslint@releases/v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        patterns: src/**.ts

    # FIXME:
    # - run: npm test

    # - uses: ./

  publish:
    if: startsWith(github.ref, 'refs/heads/versions/')
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v1

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          # TODO: make dashes vs. underscores consistent
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true